### ISSUE TITLE
vidsrc.me causing Segmentation fault (core dumped).

### ISSUE THREAD

**Issue by zzzjano** [giammirove/videogatherer#10]
While using vidsrc.me im getting error Segmentation fault (core dumped). In other sources it doesnt happen. It has something to do with js code execution from vidsrc.me (it happens for movie tmdb id 1022789, not every time)

`PID 460085 received SIGSEGV for address: 0xe58 /home/ubuntu/flix/backend_new/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x3004)[0xe32c00023004] linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xe32c02dfa9d0] node(_ZN2v88internal23StringTableInsertionKeyC2EPNS0_7IsolateENS0_6HandleINS0_6StringEEENS0_27DeserializingUserCodeOptionE+0x9c)[0x149f38c] node(_ZN2v88internal22SharedHeapDeserializer22DeserializeStringTableEv+0x90)[0x14b5570] node(_ZN2v88internal22SharedHeapDeserializer22DeserializeIntoIsolateEv+0x70)[0x14b5610] node(_ZN2v88internal7Isolate4InitEPNS0_12SnapshotDataES3_S3_b+0xab8)[0x1006038] node[0x14b735c] node(_ZN2v87Isolate10InitializeEPS0_RKNS0_12CreateParamsE+0x144)[0xe98c14] /home/ubuntu/flix/backend_new/node_modules/isolated-vm/out/isolated_vm.node(_ZN3ivm18IsolateEnvironment11IsolateCtorEmSt10shared_ptrIN2v812BackingStoreEEm+0x324)[0xe32be9e1dac8] /home/ubuntu/flix/backend_new/node_modules/isolated-vm/out/isolated_vm.node(_ZN3ivm13IsolateHandle3NewEN2v810MaybeLocalINS1_6ObjectEEE+0x438)[0xe32be9e56f88] /home/ubuntu/flix/backend_new/node_modules/isolated-vm/out/isolated_vm.node(ZN3ivm6detail10RunBarrierIZNS0_13CallbackMakerIPFN2v85LocalINS3_5ValueEEES6_NS3_10MaybeLocalINS3_6ObjectEEEEXadL_ZNS0_23ConstructorFunctionImplIFSt10unique_ptrINS_11ClassHandleESt14default_deleteISE_EES9_EE6InvokeIXadL_ZNS_13IsolateHandle3NewES9_EEEES6_S6_S9_EELin1EJRKNS3_20FunctionCallbackInfoIS5_EEEE8CallbackESP_EUlvE_EEvT+0x98)[0xe32be9e61ea8] /home/ubuntu/flix/backend_new/node_modules/isolated-vm/out/isolated_vm.node(_ZN3ivm19ConstructorFunctionIPFSt10unique_ptrINS_11ClassHandleESt14default_deleteIS2_EEN2v810MaybeLocalINS6_6ObjectEEEEXadL_ZNS_13IsolateHandle3NewES9_EEE5EntryERKNS6_20FunctionCallbackInfoINS6_5ValueEEE+0x54)[0xe32be9e62434] node(_ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE+0x158)[0xeea8d8] node[0xeeae4c] node(_ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE+0xbc)[0xeeb43c] node[0x1868964] Segmentation fault (core dumped)`

**Comment by giammirove** [comment]
I need more details to reproduce and investigate the problem.
Could you give me:
- distro 
- nodejs version
- package.json
- any modifications to the source code (if any)

**Comment by zzzjano** [comment]
I realized that the issue was due to an old version of Node.js where WebCrypto wasn't functioning. After upgrading Node.js, everything works fine.
