### ISSUE TITLE
add new site 

### ISSUE THREAD

**Issue by aston314** [giammirove/videogatherer#6]
can add https://vidsrc.cc/?

**Comment by giammirove** [comment]
Added in https://github.com/giammirove/videogatherer/commit/b2d4a97a1e4ac167438b3a8e0ad8e5e83d937052

**Comment by aston314** [comment]
Thank you, but it often changes its key. I don’t know if it can be obtained dynamically. I am talking about the key being xxx.

function enc(input: string): string {
  return encodeURIComponent(btoa(rc4("xxx", input)));
}

**Comment by giammirove** [comment]
Hi, the key did not change in the last 7 days, I have a way to collect it from the source, but I need to see it changing one or two more times to be sure about my algo.
